#!make -f
.DELETE_ON_ERROR:

all: corpus/jwikipedia10k.corpus corpus/naist-jdic.corpus corpus/naist-jdic-simple.corpus

corpus/%.corpus: corpus_source/%.src Makefile.corpus corpus_convert.py
	python3 corpus_convert.py $< $@

corpus/words.corpus: /usr/share/dict/words
	cat $< | grep -v \''s?$' | sort | uniq > $@
