#!make -f
# note: this Makefile is not needed for general use.
# Files are already converted in the source repository.

.DELETE_ON_ERROR:

DIAG=
# DIAG=--diag

CORPUS=jwikipedia10k naist-jdic naist-jdic-simple crossword

all: $(patsubst %,corpus/%.corpus,$(CORPUS))

corpus/%.corpus: corpus_source/%.src corpus_convert.py
	python3 corpus_convert.py $(DIAG) $< $@

corpus/words.corpus: /usr/share/dict/words
	cat $< | grep -v \''s?$' | sort | uniq > $@
